### Get all users
GET http://localhost:3002/api/v2/users

### Create a new user
POST http://localhost:3002/api/v2/users
Content-Type: application/json

{
  "username": "Arm14",
  "email": "arm14@mail.com",
  "password": "arm123456"
}

### Update all field a user
PUT http://localhost:3002/api/v2/users/6a0be447602ce46600d913ae
Content-Type: application/json

{
  "username": "Arm14Update",
  "email": "arm14-2@mail.com",
  "password": "armpw14-2"
}

### Delete user by id
DELETE http://localhost:3002/api/v2/users/6a0be447602ce46600d913ae