### Get all users
GET http://localhost:3002/api/v1/users

### Create a new user
POST http://localhost:3002/api/v1/users
Content-Type: application/json

{
  "username": "Arm5",
  "email": "arm5@mail.com",
  "password": "armpw123"
}

### Update all field a user
PUT http://localhost:3002/api/v1/users/1
Content-Type: application/json

{
  "username": "Arm6",
  "email": "arm6@mail.com",
  "password": "armpw666"
}

### Delete user by id
DELETE http://localhost:3002/api/v1/users/1